name: Build

on:
  push:

jobs:
  build:
    name: Lint, build, test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Tests
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Release
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.repository != 'hands-in/library-template-typescript'
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          HUSKY: 0

      - name: Create the docs
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.repository != 'hands-in/library-template-typescript'
        run: pnpm run docs

      - name: Collect coverage report
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.repository != 'hands-in/library-template-typescript'
        run: pnpm run test:coverage

      - name: Create Coverage Badges
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.repository != 'hands-in/library-template-typescript'
        uses: jaywcjlove/coverage-badges-cli@daf59ef2ce43c8e4974150356d7250b4c41b4f93
        with:
          source: coverage/coverage-summary.json
          output: coverage/lcov-report/badges.svg

      - name: Prepare folder for gh-pages
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.repository != 'hands-in/library-template-typescript'
        run: |
          mkdir gh-pages
          mv docs ./gh-pages/docs
          mv coverage/lcov-report ./gh-pages/coverage

      - name: Deploy 🚀
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.repository != 'hands-in/library-template-typescript'
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
        with:
          branch: gh-pages
          folder: gh-pages