name: Run on pull requests

on:
  pull_request:

jobs:
  check-test-coverage:
    runs-on: ubuntu-20.04
    name: Run tests & check coverage
    permissions:
      checks: write
      pull-requests: write
      contents: read # for private repos
    steps:
      - uses: actions/checkout@v3
      - name: Jest coverage comment
        id: coverage
        uses: ArtiomTr/jest-coverage-report-action@f1a1382101d9b92b38e3df05c9ed89a834af97c8
        with:
          package-manager: yarn
          output: report-markdown
      - run: npm run test:coverage
      - name: Read coverage text report
        uses: fingerprintjs/action-coverage-report-md@v1
        id: coverage-md
      - uses: marocchino/sticky-pull-request-comment@44e0bad81007ecff41ba26d1cbf49a0267d28e9d
        with:
          message: |
            ${{ steps.coverage.outputs.report }}
            <details>
              <summary>Show full coverage report</summary>

              ${{ steps.coverage-md.outputs.markdownReport }}
            </details>
